# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# Rust Install

  - name: Rust Install
    init: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      gp sync-done rustinstall
    command: |
      source $HOME/.cargo/env 
      rustup component add rustfmt
      openMode: tab-after

# Anchor Install 
  - name: Solana Install
    init: |
      gp sync-await rustinstall
      sh -c "$(curl -sSfL https://release.solana.com/v1.9.4/install)"
      export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH" 
      source ~/.bashrc 
      echo $PATH | grep solana 
    command:  solana
    openMode: tab-after

# Rust Update 
  - name: Rust update 
    init : |
      gp sync-await rustinstall
      rustup default nightly
      rustup update  
    openMode: split-right

# NPM Update 
  - name: NPM Update
    init: |
      npm update -g 
      gp sync-done npmy
    command: npm --version
    openMode: tab-after

# Anchor Install 
  - name: Anchor Install 
    init: |
      gp sync-await npmy
      npm i -g @project-serum/anchor-cli
    command: anchor 
    openMode: split-right

# NPM Server Install
  - name: Install NPM Server
    init: |
      gp sync-await npmy
      npm install --global http-server
    openMode: split-right 


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000-9000 
    onOpen: open-preview
